a=input("Enter first number:")
b=input("Enter second number:")
sum=int(a)+int(b)
print("The sum is:",sum)
diff=int(a)-int(b)
print("The difference is:",diff)
prod=int(a)*int(b)
print("The product is:",prod)
quot=int(a)/int(b)
print("The quotient is:",quot)
rem=int(a)%int(b)
print("The remainder is:",rem)
exp=int(a)**int(b)
print("The exponent is:",exp)
flo=int(a)//int(b)
print("The floor value is:",flo)
#This is a practise code for basic arithmetic operations
vivek=int(a)+int(b)
print("The vivek is:",vivek)